# Site settings
title: The Padre Hotel Bakersfield CA | Hotels in Bakersfield
email: TEAM@THEPADREHOTEL.COM
phone: 661-427-4900
description: > # this means to ignore newlines until "baseurl:"
The Padre is a sophisticated boutique hotel with restaurants, nightlife and many more facilities. Book your stay at Bakersfield’s best hotel, the Padre Hotel.

permalink: pretty
 
default_lang: 'en'

languages: ['en']
 
port: 4001
exclude:
  - 'sitemap.json'
  
keep_files: ['assets']
rsync_copy: ['_assets']
