# Site settings
title: padre
email:
phone:
description: > # this means to ignore newlines until "baseurl:"
url                      : "http://www.thepadrehotel.com/"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "TravelTripperWeb/padre"

permalink: pretty

default_lang: 'en'

languages: ['en']

port: 8080

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - Makefile
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - sitemap.json
  - tmp
  - gulpfile.js

# Sass/SCSS
sass:
    load_paths:
        - _sass
    style: compressed
 
keep_files: ['assets']
rsync_copy: ['_assets']
booking_widget_url: https://thepadrehotel.reztrip.com/mobile