# Site settings
title: 
email:  
phone:  
description: > # this means to ignore newlines until "baseurl:"
 
permalink: pretty
 
default_lang: 'en'

languages: ['en']
 
port: 4001
exclude:
  - 'sitemap.json'
  
keep_files: ['assets']
rsync_copy: ['_assets']
