# Site settings
title:
email:
phone:
description: > # this means to ignore newlines until "baseurl:"

permalink: pretty

default_lang: 'en'

languages: ['en']

port: 8080


keep_files: ['assets']
rsync_copy: ['_assets']
booking_widget_url: https://thepadrehotel.reztrip.com/mobile
